# https://blowfish.page/docs/configuration/
theme = "blowfish"
baseURL = "https://docs.fflegacy.club/"
title = "FFLegacy Docs"
colorScheme = "forest"
defaultSocialImage = "fflegacy.png"

[outputs]
home = ["HTML", "RSS", "JSON"]